### ISSUE TITLE
ERROR: Error reading Account

### ISSUE THREAD

**Issue by ppope** [mihaics/opengts#1]
Greetings,

Really cool and useful project. Many thanks for the work.

Following your comment [here](https://sourceforge.net/p/opengts/discussion/579834/thread/7bab6bd1/), I attempted to login into http://localhost:8080/track/Track with account "sysadmin" and password "sysadmin". 

This failed with `ERROR: Error reading Account` (translated). I have both cookies and javascript enabled. The containers start successfully. Output [here](https://gist.github.com/ppope/871db476891107fe0358398c80d05729).

Can you assist?

**Comment by mihaics** [comment]
Hi, I will investigate, it is clear that the database was not correct initialised.
Is this the first run, with clean images?

**Comment by ppope** [comment]
Yes, the images were clean. To verify, I removed them, repulled, and obtained the same error.

Let me know how else I can help.

**Comment by mihaics** [comment]
It is pretty clear what happens: mysql is not yet initialized when opengts script for database is running to setup the user. Funny that I did not get into this issue on my laptop, because compiling opengts takes longer (on my machine) than database initialization. 
I patched the script (hoping that the return code of dbAdmin.pl is correct), but I did not simulated the issue, yet. Please check with the new images from docker hub, and the new docker-compose.yml file. (on my laptop still runs fine :) )
If I will have time, I will make extensive tests next week.

Thanks, 
Mihai

**Comment by mihaics** [comment]
fixed (I think...at least this issue :) ), many thanks for helping me to improve the images.

Mihai

**Comment by ppope** [comment]
Great. Are the new changes pushed to repo? I will test.

**Comment by mihaics** [comment]
Yes, docker hub already built the images from github. But don't forget to pull both, mysql and opengts.

**Comment by ppope** [comment]
Beautiful. Login works without error. 

Thanks again!
